version: '3.4'

services:
  forumdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
